### ISSUE TITLE
Not compatible with theme cybertron

### ISSUE THREAD

**Issue by KALKI-the-avataar** [gitobsidiantutorial/obsidian-tabs#1]

**Comment by gitobsidiantutorial** [comment]
I added a [compatch ](https://raw.githubusercontent.com/gitobsidiantutorial/obsidian-tabs/main/compatch_cybertron_theme.css)to get it looking better with cybertron 
![image](https://user-images.githubusercontent.com/81381984/113465589-71e5df80-9435-11eb-896b-1457e02b490a.png)

**Comment by KALKI-the-avataar** [comment]
thanks
