### ISSUE TITLE
css: change the the tabs hover cursor

### ISSUE THREAD

**Issue by renmu123** [gitobsidiantutorial/obsidian-tabs#10]
Now, when l move the cursor the tabs, the cursor mode is `text`. 
lt may means now l am editing the text instead of changing the tab . 
Change the mode to `pointer`(like vscode) or `context-menu`(like chrome) may be more suitable.

**Comment by gitobsidiantutorial** [comment]
`cursor: context-menu` has been implemented in version 1.0.5
