### ISSUE TITLE
Bug in correlation with Focus Mode Plugin

### ISSUE THREAD

**Issue by tim-hilde** [gitobsidiantutorial/obsidian-tabs#14]
Using version your plugin leads to a bug in the tab bar. The video shows it quite nicely. Disabling the [Focus Mode Plugin](https://github.com/ryanpcmcquen/obsidian-focus-mode) solves the issue. I've also opened an issue there: https://github.com/ryanpcmcquen/obsidian-focus-mode/issues/12

https://user-images.githubusercontent.com/44113468/119495915-398ebd80-bd63-11eb-8e8b-99fa5f95d440.mov

**Comment by shaggyfeng** [comment]
I love Tabs. But this is happening when Focus Mode are enabled.

**Comment by ryanpcmcquen** [comment]
Focus Mode is almost purely CSS, so this is a really weird bug ...

**Comment by gitobsidiantutorial** [comment]
I see the issue, it's because pane headers get hidden in focus mode, I think I'll have a fix soon ™

**Comment by gitobsidiantutorial** [comment]
@ryanpcmcquen I see now that the proposed fix for focus mode is implemented differently in the CSS.

I like the fix in your repo more, so I think I'm going to roll back my update and let your fix take precedence !

**Comment by ryanpcmcquen** [comment]
Oh! I just reverted that and didn't release. Should I unrevert?

**Comment by ryanpcmcquen** [comment]
Okay, [1.6.0](https://github.com/ryanpcmcquen/obsidian-focus-mode/releases/tag/1.6.0) is out! Thanks to @AidenLx!

**Comment by gitobsidiantutorial** [comment]
Sorry about that Ryan, I should have communicated that earlier 🙃

Glad we got that sorted!
