### ISSUE TITLE
Theme compatibility request: California Coast Obsidian Theme

### ISSUE THREAD

**Issue by retgits** [gitobsidiantutorial/obsidian-tabs#15]
I totally dig the idea of having tabs in Obsidian, I think it would greatly improve my workflow unfortunately it doesn't seem to work with the theme I selected [California Coast Obsidian Theme](https://github.com/mgmeyers/obsidian-california-coast-theme). The tabs don't seem to show in the center pane.

**Comment by gitobsidiantutorial** [comment]
![image](https://user-images.githubusercontent.com/81381984/121015813-b4140000-c79b-11eb-94a5-61a2d8e6e404.png)

[Compatch now available!](https://raw.githubusercontent.com/gitobsidiantutorial/obsidian-tabs/main/compatch_california_coast.css)
