### ISSUE TITLE
Obsidian Tabs + Workspaces (core plugin) 

### ISSUE THREAD

**Issue by FelipeRearden** [gitobsidiantutorial/obsidian-tabs#17]
Hello @foreveryone1 and @gitobsidiantutorial ! 

I’m sorry to bother you, I have a doubt about Obsidian Tabs that I wanna share with you. I made a [post on the forum](https://forum.obsidian.md/t/workspaces-core-plugin-obsidian-tabs-a-little-adjustment/19434) about a integration between Obsidian Tabs and Workspaces (core plug-in) 

My suggestion is that the Workspaces plug-in  “remembers”  the Obsidian Tabs status (toggle [ON/OFF]) when I’m saving a Workspace. This way I don’t have to change Obsidian Tabs between Workspaces (Workspace A uses Obsidian Tabs `ON` and  Workspace B uses Obsidian Tabs `OFF`).

**My question:** is there anything can be done (from the Obsidian Tabs standpoint) to make this feature happen? Maybe Obsidian already has a part of the code that Obsidian Tabs can use to  save the toggle status. 

Since Silver and Licat has so many more important issues to deal with that I’m afraid that this integration can’t happen in the short term. That’s why I decide to talk to you to see if anything can be done from you end. 

I love Obsidian Tabs and I think this integration with Workspaces would be extremely powerful. 
 
Sorry again to bother you with this. Thanks for reading this! 

Have a great day!

**Comment by gitobsidiantutorial** [comment]
That's a really thorough and well thought out feature request, I'm sorry to say that changing the behaviour of the workspace plugin is a bit out of scope right now.

**Comment by FelipeRearden** [comment]
Thanks for your reply @gitobsidiantutorial !

That's okay! At least I tried and present you a scenario between two amazing plugins. 

Maybe in the feature the workspace plug-in devs look at my post in the forum and bring this feature to us :)

Thanks for your time and have a great day! I really like Obsidian Tabs !
