### ISSUE TITLE
When i click the note in fixed pane the sliding one, get disappeard.

### ISSUE THREAD

**Issue by KALKI-the-avataar** [gitobsidiantutorial/obsidian-tabs#3]
![image](https://user-images.githubusercontent.com/80031164/113472398-9fa44600-9480-11eb-86b5-a59cb2b2c4df.png)

**Comment by gitobsidiantutorial** [comment]
> When in side-by-side view, focusing on the side tab shrinks the tabbed pane. This issue cannot be fixed purely with css, unfortunately.

It's a [known issue](https://github.com/gitobsidiantutorial/obsidian-tabs/blob/main/README.md#issues) of only using CSS. There's no way to append a class to the most recently opened 'tab' to prevent it from collapsing.

As an alternative, consider linking tabs to the fixed panes to the right.

**Comment by gitobsidiantutorial** [comment]
Woops, this was the actual thread I should have replied to!

The plugin version now allows this to be possible!
