### ISSUE TITLE
Siding view doesn't work

### ISSUE THREAD

**Issue by Mara-Li** [gitobsidiantutorial/obsidian-tabs#4]
Vertical view doesn't work. See gif for more information : 
![tab](https://user-images.githubusercontent.com/30244939/115137849-bc1bb300-a028-11eb-8f9a-ee75359a487e.gif)

**Comment by gitobsidiantutorial** [comment]
This is a known issue, split views can only by created on start.

First create the horizontal view, and then create tabs by splitting panes vertically.

**Comment by Mara-Li** [comment]
Still doesn't work using the same way that the demo :(

**Comment by gitobsidiantutorial** [comment]
You can't create a split view when only one pane is open?

**Comment by Mara-Li** [comment]
Sorry, I try but it doesn't work ;/ Check the gif below

https://i.imgur.com/DlnmGvK.gif

**Comment by gitobsidiantutorial** [comment]
Is this with the horizontal splits setting disabled?

![image](https://user-images.githubusercontent.com/81381984/115269888-09d51000-a13c-11eb-9e51-3598dc24bac0.png)

If so, could you use the default theme and tell me if this issue still occurs? If it no longer occurs, could you tell me which theme you're using, so I can make a compatch?

**Comment by Mara-Li** [comment]
Okay, disabling proper horizontal make it work ! It's a little strange to be honest, but okay

**Comment by gitobsidiantutorial** [comment]
It's because 'horizontal splits' in the default interface are the splits which are stacked on top of one another.
