### ISSUE TITLE
Tabs not appearing

### ISSUE THREAD

**Issue by im-richard** [gitobsidiantutorial/obsidian-tabs#44]
Hey,

I apologize if this is such a noob question, but is their anything in particular to get pages to open in different tabs? I have it installed, but each time I click a page; it just opens that one page with zero tabs.

https://user-images.githubusercontent.com/13498846/183292257-fb3269ea-0355-44f0-83fd-98927687a033.mp4

Or any known incompatibility issues with other plugins?

Using default theme (Dark).
v0.15.9

**Comment by chrarnold** [comment]
I have the same problem, it doesnt seem to work for me at all. Opening a new note just replaces the old one...I am uing the "Things" theme. Newest versions

**Comment by im-richard** [comment]
> I have the same problem, it doesnt seem to work for me at all. Opening a new note just replaces the old one...I am uing the "Things" theme. Newest versions

I've tried a large number of themes to get it to work. I've disabled every addon, I've reset the program.
It appears to be an issue directly between the program and plugin.

**Comment by LaserStefan** [comment]
Same here. Perhaps this is a very recent issue? Tabs were working the day before yesterday, now they won't pop up. I can only get one tab on top if I pin a pane, but that's not how it's supposed to work. I've tried changing many settings, disabling all plugins one by one, and deinstalling. No idea what to do.

/Edit. Ok. stupid me. It works when I crtl+click on items. Hope that helps.

**Comment by im-richard** [comment]
> /Edit. Ok. stupid me. It works when I crtl+click on items. Hope that helps.

Ahhhh, yes. That appears to work. I read those docs at least 4 times. I must have missed doing CTRL + Click.

After 3 days it's finally working. Thanks!

Only minor complaint I have is I wish it would put the tabs for the opened documents in a static position. When I click on a tab, the tab name switches to the name of the other document instead of just showing two tabs for the two opened documents. I've been used to VSCode tabs for a long time so this will take some getting used to.

**Comment by chrarnold** [comment]
Indeed, Ctrl + Click works. However when clicking through the tabs, the tab name of the active tab is wrong, which is very confusing and prevents me from using it unfortunately. Is this a known bug, should we file it separately?

**Comment by LaserStefan** [comment]
> Indeed, Ctrl + Click works. However when clicking through the tabs, the tab name of the active tab is wrong, which is very confusing and prevents me from using it unfortunately. Is this a known bug, should we file it separately?

Great that we could help each other out (I wasted many hours on this). However, I don't have the file name bug you report... Perhaps file a separate issue. @chrarnold 

And I would love to have the static position too, @im-richard.

**Comment by im-richard** [comment]
> And I would love to have the static position too, @im-richard.

I'll check through the issues list and see if this feature request has been submitted already; if not, I'll drop one in.
Thanks again for the tip. I've been trying for three days to figure out why it's not working, with hours of shuffling plugins around thinking something else was breaking it lol

**Comment by im-richard** [comment]
Issue resolved.

**Solution:** Use CTRL + LMB to open each document in a tab.

Issues #45 and #46 opened to describe tab bug / feature request.

Thanks again @LaserStefan
