### ISSUE TITLE
(Bug) the tab number css is gone

### ISSUE THREAD

**Issue by jokysatria** [gitobsidiantutorial/obsidian-tabs#9]
Hi, after toggle tab update, I just realized that the tabs number and some other styling are gone.

![image](https://user-images.githubusercontent.com/69371378/116011354-c18f8380-a64e-11eb-9997-683c9d3ce640.png)

**Comment by gitobsidiantutorial** [comment]
My mistake, I seem to have slipped up when formatting the CSS for the new update. This has been fixed in v 1.0.4
Thanks for notifying me!
